cadena = ' \tSoy una cadena\t\n\tSoy una cadena tabulada \n Soy otra cadena'
print ("---Cadena Original---")
print (cadena)
print("----")
print ("---Cadena con strip---")
cadena_uno = cadena.strip()
print (cadena_uno)
print("----")
print ("---Cadena con .replace---")
cadena_dos = cadena.replace("  ","").replace("\t","").replace("\n"," ")
print (cadena_dos)
print("----")
print ("---Cadena con join---")
cadena_tres = " ".join(cadena.split())
print (cadena_tres)